const playerListUrl='assets/players.json';
const list=document.querySelector('#playerList'),search=document.querySelector('#playerSearch');
let players=[];

function render(q=''){list.innerHTML=players.filter(p=>p.toLowerCase().includes(q.toLowerCase())).map(p=>`<span class="player">${p}</span>`).join('')||'<span class="source-note">No matching name in the supplied list.</span>'}
async function loadPlayers(){try{const response=await fetch(playerListUrl,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data))throw new Error('Invalid player data');players=data.filter(p=>typeof p==='string');render()}catch(error){list.innerHTML='<span class="source-note">Former player list is temporarily unavailable.</span>';console.warn('Player data could not be loaded',error)}}
search.addEventListener('input',e=>render(e.target.value));loadPlayers();
const menu=document.querySelector('.menu'),links=document.querySelector('#navlinks');menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open)});links.addEventListener('click',e=>{if(e.target.matches('a')){links.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e))}else document.querySelectorAll('.reveal').forEach(e=>e.classList.add('visible'));
const modal=document.querySelector('.video-modal'),video=modal.querySelector('video'),openVideo=document.querySelector('[data-open-video]'),closeVideo=modal.querySelector('[data-close-video]');function showVideo(e){e.preventDefault();modal.hidden=false;document.body.style.overflow='hidden';closeVideo.focus()}function hideVideo(){modal.hidden=true;video.pause();video.currentTime=0;document.body.style.overflow=''}openVideo.addEventListener('click',showVideo);closeVideo.addEventListener('click',hideVideo);modal.addEventListener('click',e=>{if(e.target===modal)hideVideo()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)hideVideo()});
